1>------ Build started: Project: Project MVCs (Visual Studio 2010), Configuration: Debug Win32 ------
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>MVC_Model.obj : error LNK2005: "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z) already defined in MVC_Controller.obj
1>MVC_View.obj : error LNK2005: "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z) already defined in MVC_Controller.obj
1>UserInterface HUD.lib(HUD.obj) : error LNK2005: "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z) already defined in MVC_Controller.obj
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glTexImage2D@36 referenced in function "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z)
1>MVC_Controller.obj : error LNK2001: unresolved external symbol __imp__glTexImage2D@36
1>MVC_Model.obj : error LNK2001: unresolved external symbol __imp__glTexImage2D@36
1>MVC_View.obj : error LNK2001: unresolved external symbol __imp__glTexImage2D@36
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glTexImage2D@36
1>MVC_Controller.obj : error LNK2019: unresolved external symbol __imp__glTexParameterf@12 referenced in function "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z)
1>MVC_Model.obj : error LNK2001: unresolved external symbol __imp__glTexParameterf@12
1>MVC_View.obj : error LNK2001: unresolved external symbol __imp__glTexParameterf@12
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glTexParameterf@12
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glBindTexture@8
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glBindTexture@8 referenced in function "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z)
1>MVC_Controller.obj : error LNK2001: unresolved external symbol __imp__glBindTexture@8
1>MVC_Model.obj : error LNK2001: unresolved external symbol __imp__glBindTexture@8
1>MVC_View.obj : error LNK2001: unresolved external symbol __imp__glBindTexture@8
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glBindTexture@8
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glGenTextures@8
1>MVC_Controller.obj : error LNK2019: unresolved external symbol __imp__glGenTextures@8 referenced in function "bool __cdecl LoadTGA(struct TextureImage *,char *)" (?LoadTGA@@YA_NPAUTextureImage@@PAD@Z)
1>MVC_Model.obj : error LNK2001: unresolved external symbol __imp__glGenTextures@8
1>MVC_View.obj : error LNK2001: unresolved external symbol __imp__glGenTextures@8
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glGenTextures@8
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: void __thiscall MVC_View::KillGLWindow(void)" (?KillGLWindow@MVC_View@@QAEXXZ) referenced in function "public: int __thiscall MVC_Controller::RunMainLoop(void)" (?RunMainLoop@MVC_Controller@@QAEHXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: int __thiscall MVC_View::CreateGLWindow(char *,int,int,int)" (?CreateGLWindow@MVC_View@@QAEHPADHHH@Z) referenced in function "public: int __thiscall MVC_Controller::RunMainLoop(void)" (?RunMainLoop@MVC_Controller@@QAEHXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: void __thiscall MVC_View::GetDefaultRes(int &,int &)" (?GetDefaultRes@MVC_View@@QAEXAAH0@Z) referenced in function "public: int __thiscall MVC_Controller::RunMainLoop(void)" (?RunMainLoop@MVC_Controller@@QAEHXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: void __thiscall MVC_View::SetFullScreen(bool)" (?SetFullScreen@MVC_View@@QAEX_N@Z) referenced in function "public: int __thiscall MVC_Controller::RunMainLoop(void)" (?RunMainLoop@MVC_Controller@@QAEHXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: bool __thiscall MVC_View::ToggleFullScreen(void)" (?ToggleFullScreen@MVC_View@@QAE_NXZ) referenced in function "public: bool __thiscall MVC_Controller::ProcessInput(void)" (?ProcessInput@MVC_Controller@@QAE_NXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: bool __thiscall MVC_View::RunFullScreen(void)" (?RunFullScreen@MVC_View@@QAE_NXZ) referenced in function "public: bool __thiscall MVC_Controller::ProcessInput(void)" (?ProcessInput@MVC_Controller@@QAE_NXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: bool __thiscall MVC_View::IsQuitGame(void)" (?IsQuitGame@MVC_View@@QAE_NXZ) referenced in function "public: bool __thiscall MVC_Controller::ProcessInput(void)" (?ProcessInput@MVC_Controller@@QAE_NXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: void __thiscall MVC_View::GetSize(int *,int *)" (?GetSize@MVC_View@@QAEXPAH0@Z) referenced in function "protected: void __thiscall MVC_Controller::ProcMouse(void)" (?ProcMouse@MVC_Controller@@IAEXXZ)
1>MVC_Controller.obj : error LNK2019: unresolved external symbol "public: bool * __thiscall MVC_View::GetKeyBuffer(void)" (?GetKeyBuffer@MVC_View@@QAEPA_NXZ) referenced in function "protected: void __thiscall MVC_Controller::ProcKeyboard(void)" (?ProcKeyboard@MVC_Controller@@IAEXXZ)
1>MVC_Model.obj : error LNK2019: unresolved external symbol __imp__glDisable@4 referenced in function "public: bool __thiscall MVC_Model::InitPhase2(void)" (?InitPhase2@MVC_Model@@QAE_NXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glDisable@4
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glDisable@4
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glDisable@4
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glEnable@4 referenced in function "public: void __thiscall HUD::DrawMinimap(void)" (?DrawMinimap@HUD@@QAEXXZ)
1>MVC_Model.obj : error LNK2001: unresolved external symbol __imp__glEnable@4
1>MVC_View.obj : error LNK2001: unresolved external symbol __imp__glEnable@4
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glEnable@4
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glEnable@4
1>MVC_View.obj : error LNK2001: unresolved external symbol "private: virtual long __stdcall MVC_View::MsgProc(struct HWND__ *,unsigned int,unsigned int,long)" (?MsgProc@MVC_View@@EAGJPAUHWND__@@IIJ@Z)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glColor3f@12 referenced in function "public: int __thiscall MVC_View::Draw(void)" (?Draw@MVC_View@@QAEHXZ)
1>Base Entity.lib(ObjectModel.obj) : error LNK2001: unresolved external symbol __imp__glColor3f@12
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glColor3f@12
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glLoadIdentity@0 referenced in function "public: int __thiscall MVC_View::Draw(void)" (?Draw@MVC_View@@QAEHXZ)
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glLoadIdentity@0
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glClear@4 referenced in function "public: int __thiscall MVC_View::Draw(void)" (?Draw@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol "private: void __thiscall MVC_View::BuildFont(void)" (?BuildFont@MVC_View@@AAEXXZ) referenced in function "public: int __thiscall MVC_View::InitGL(void)" (?InitGL@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glHint@8 referenced in function "public: int __thiscall MVC_View::InitGL(void)" (?InitGL@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glDepthFunc@4 referenced in function "public: int __thiscall MVC_View::InitGL(void)" (?InitGL@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glClearDepth@8 referenced in function "public: int __thiscall MVC_View::InitGL(void)" (?InitGL@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glClearColor@16 referenced in function "public: int __thiscall MVC_View::InitGL(void)" (?InitGL@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glShadeModel@4 referenced in function "public: int __thiscall MVC_View::InitGL(void)" (?InitGL@MVC_View@@QAEHXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glPopMatrix@0 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>Base Entity.lib(ObjectModel.obj) : error LNK2001: unresolved external symbol __imp__glPopMatrix@0
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glPopMatrix@0
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glEnd@0 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glEnd@0
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glEnd@0
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glEnd@0
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glVertex3f@12 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glVertex3f@12
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glVertex3f@12
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glBegin@4 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2001: unresolved external symbol __imp__glBegin@4
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glBegin@4
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glBegin@4
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glRotatef@16 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glRotatef@16
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glTranslatef@12 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>Base Entity.lib(ObjectModel.obj) : error LNK2001: unresolved external symbol __imp__glTranslatef@12
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glTranslatef@12
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glPushMatrix@0 referenced in function "public: void __thiscall MVC_View::DrawObject(void)" (?DrawObject@MVC_View@@QAEXXZ)
1>Base Entity.lib(ObjectModel.obj) : error LNK2001: unresolved external symbol __imp__glPushMatrix@0
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glPushMatrix@0
1>MVC_View.obj : error LNK2019: unresolved external symbol "private: void __cdecl MVC_View::Printw(float,float,char const *,...)" (?Printw@MVC_View@@AAAXMMPBDZZ) referenced in function "public: void __thiscall MVC_View::DrawScene(void)" (?DrawScene@MVC_View@@QAEXXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glLineWidth@4 referenced in function "public: void __thiscall MVC_View::Draw3DSGrid(void)" (?Draw3DSGrid@MVC_View@@QAEXXZ)
1>MVC_View.obj : error LNK2019: unresolved external symbol __imp__glColor3ub@12 referenced in function "public: void __thiscall MVC_View::Draw3DSGrid(void)" (?Draw3DSGrid@MVC_View@@QAEXXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__wglGetProcAddress@4 referenced in function "void __cdecl InitOpenGL_Extensions(void)" (?InitOpenGL_Extensions@@YAXXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glGetString@4 referenced in function "void __cdecl InitOpenGL_Extensions(void)" (?InitOpenGL_Extensions@@YAXXZ)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glColorPointer@16 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glTexEnvf@12 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glDisableClientState@4 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glDrawElements@16 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glTexCoordPointer@16 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glNormalPointer@12 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glEnableClientState@4 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glVertexPointer@16 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glCallList@4 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glNormal3f@12 referenced in function _DrawOBJ
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glTexCoord2f@8 referenced in function _DrawOBJ
1>Sky Box.lib(SkyBox.obj) : error LNK2001: unresolved external symbol __imp__glTexCoord2f@8
1>UserInterface HUD.lib(HUD.obj) : error LNK2001: unresolved external symbol __imp__glTexCoord2f@8
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glDeleteLists@8 referenced in function "void __cdecl DeleteMesh(struct _ObjMesh *)" (?DeleteMesh@@YAXPAU_ObjMesh@@@Z)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glTexParameteri@12 referenced in function "unsigned int __cdecl MakeGlTexture(unsigned char * const,int,int,int)" (?MakeGlTexture@@YAIQAEHHH@Z)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glPixelStorei@8 referenced in function "unsigned int __cdecl MakeGlTexture(unsigned char * const,int,int,int)" (?MakeGlTexture@@YAIQAEHHH@Z)
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glEndList@0 referenced in function _ConvertMeshTo
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glNewList@8 referenced in function _ConvertMeshTo
1>Model and Texture Loader.lib(ObjLoader.obj) : error LNK2019: unresolved external symbol __imp__glGenLists@4 referenced in function _ConvertMeshTo
1>Sky Box.lib(SkyBox.obj) : error LNK2019: unresolved external symbol __imp__glColor4f@16 referenced in function "public: void __thiscall SkyBox::Draw(void)" (?Draw@SkyBox@@QAEXXZ)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glPolygonMode@8 referenced in function "public: void __thiscall HUD::DrawHealthBar(int,int)" (?DrawHealthBar@HUD@@QAEXHH@Z)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glVertex2f@8 referenced in function "public: void __thiscall HUD::DrawHealthBar(int,int)" (?DrawHealthBar@HUD@@QAEXHH@Z)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glBlendFunc@8 referenced in function "public: void __thiscall HUD::DrawMinimap(void)" (?DrawMinimap@HUD@@QAEXXZ)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glStencilFunc@12 referenced in function "public: void __thiscall HUD::DrawMinimap(void)" (?DrawMinimap@HUD@@QAEXXZ)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glStencilOp@12 referenced in function "public: void __thiscall HUD::DrawMinimap(void)" (?DrawMinimap@HUD@@QAEXXZ)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glOrtho@48 referenced in function "public: void __thiscall HUD::SetHUD(bool)" (?SetHUD@HUD@@QAEX_N@Z)
1>UserInterface HUD.lib(HUD.obj) : error LNK2019: unresolved external symbol __imp__glMatrixMode@4 referenced in function "public: void __thiscall HUD::SetHUD(bool)" (?SetHUD@HUD@@QAEX_N@Z)
1>MSVCRTD.lib(crtexe.obj) : error LNK2019: unresolved external symbol _main referenced in function ___tmainCRTStartup
1>C:\Users\132067D\Documents\GitHub\AGDev-Assignment-2\Main\Debug\Project MVCs.exe : fatal error LNK1120: 63 unresolved externals
========== Build: 0 succeeded, 1 failed, 11 up-to-date, 0 skipped ==========
